### ISSUE TITLE
cURL apt repository

### ISSUE THREAD

**Issue by 1995parham** [AUT-CEIT/free.sh#2]
sometimes we have ubuntu but there is not curl on 🤔  can you add some docs about how to use
AUT apt repository for cURL installation?

**Comment by pi0** [comment]
Right now I'm working on an internet access solution for Linux based servers so curl problem will be resolved too :D Will keep you informed you soon :))

**Comment by 1995parham** [comment]
Thanks 🙌

**Comment by Tabrizian** [comment]
But how?!

**Comment by 1995parham** [comment]
🤔 He let us know when the times come
